//------------------------------------------------------------------------------
// <auto-generated>
//     ?????????
//     ?????:4.0.30319.42000
//
//     ???????????????????????
//     ????????????????
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Effects;
using System.Windows.Media.Media3D;


namespace Huya.VideoPlayer.Module.Barrage.Sharder
{
	
	public class FadeInWeight2Effect : ShaderEffect {
		public static readonly DependencyProperty InputProperty = ShaderEffect.RegisterPixelShaderSamplerProperty("Input", typeof(FadeInWeight2Effect), 0);
		public static readonly DependencyProperty ImgFadeXProperty = DependencyProperty.Register("ImgFadeX", typeof(double), typeof(FadeInWeight2Effect), new UIPropertyMetadata(((double)(0.85D)), PixelShaderConstantCallback(0)));
		public static readonly DependencyProperty ImgFadeY_topProperty = DependencyProperty.Register("ImgFadeY_top", typeof(double), typeof(FadeInWeight2Effect), new UIPropertyMetadata(((double)(0.85D)), PixelShaderConstantCallback(1)));
		public static readonly DependencyProperty ImgFadeY_bottomProperty = DependencyProperty.Register("ImgFadeY_bottom", typeof(double), typeof(FadeInWeight2Effect), new UIPropertyMetadata(((double)(0.7D)), PixelShaderConstantCallback(2)));
		public FadeInWeight2Effect() {
			PixelShader pixelShader = new PixelShader();
			pixelShader.UriSource = new Uri("pack://application:,,,/Huya.VideoPlayer;component/Module/Barrage/Shader/FadeInWeight2Effect.ps");
			this.PixelShader = pixelShader;

			this.UpdateShaderValue(InputProperty);
			this.UpdateShaderValue(ImgFadeXProperty);
			this.UpdateShaderValue(ImgFadeY_topProperty);
			this.UpdateShaderValue(ImgFadeY_bottomProperty);
		}
		public Brush Input {
			get {
				return ((Brush)(this.GetValue(InputProperty)));
			}
			set {
				this.SetValue(InputProperty, value);
			}
		}
		/// <summary>ImgFadeX.</summary>
		public double ImgFadeX {
			get {
				return ((double)(this.GetValue(ImgFadeXProperty)));
			}
			set {
				this.SetValue(ImgFadeXProperty, value);
			}
		}
		/// <summary>ImgFadeY.</summary>
		public double ImgFadeY_top {
			get {
				return ((double)(this.GetValue(ImgFadeY_topProperty)));
			}
			set {
				this.SetValue(ImgFadeY_topProperty, value);
			}
		}
		/// <summary>ImgFadeY.</summary>
		public double ImgFadeY_bottom {
			get {
				return ((double)(this.GetValue(ImgFadeY_bottomProperty)));
			}
			set {
				this.SetValue(ImgFadeY_bottomProperty, value);
			}
		}
	}
}
